# Generated by Django 5.2.10 on 2026-01-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_vi', models.CharField(max_length=255, verbose_name='Vietnamese Name')),
                ('name_en', models.CharField(max_length=255, verbose_name='English Name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'staff_roles',
                'ordering': ['-created_at'],
            },
        ),
    ]
