# Generated by Django 5.2.10 on 2026-01-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
