# Generated by Django 5.2.10 on 2026-01-22 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, verbose_name='Số tài khoản')),
                ('account_name', models.CharField(max_length=255, verbose_name='Tên tài khoản')),
                ('bank_code', models.CharField(choices=[('MB', 'MBBank'), ('VCB', 'Vietcombank'), ('TCB', 'Techcombank'), ('ACB', 'ACB'), ('VTB', 'VietinBank'), ('BIDV', 'BIDV'), ('VPB', 'VPBank'), ('TPB', 'TPBank'), ('STB', 'Sacombank'), ('SHB', 'SHB'), ('MSB', 'MSB'), ('OCB', 'OCB')], max_length=10, verbose_name='Ngân hàng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('is_default', models.BooleanField(default=False, verbose_name='Tài khoản mặc định')),
                ('qr_template', models.CharField(choices=[('compact', 'Compact'), ('compact2', 'Compact 2'), ('print', 'Print'), ('qr_only', 'QR Only')], default='compact2', max_length=20, verbose_name='Template QR')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tài khoản ngân hàng',
                'verbose_name_plural': 'Tài khoản ngân hàng',
                'db_table': 'bank_accounts',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
