# Generated by Django 5.2.10 on 2026-03-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='qr_template',
            field=models.CharField(choices=[('compact', 'Compact'), ('compact2', 'Compact 2'), ('print', 'Print'), ('qr_only', 'QR Only')], default='qr_only', max_length=20, verbose_name='Template QR'),
        ),
    ]
