# Generated by Django 5.2.10 on 2026-03-08 03:17

from django.db import migrations


def update_qr_template(apps, schema_editor):
    """Update all existing bank accounts to use qr_only template"""
    BankAccount = apps.get_model('payments', 'BankAccount')
    BankAccount.objects.filter(qr_template='compact2').update(qr_template='qr_only')


def reverse_qr_template(apps, schema_editor):
    """Reverse migration - change back to compact2"""
    BankAccount = apps.get_model('payments', 'BankAccount')
    BankAccount.objects.filter(qr_template='qr_only').update(qr_template='compact2')


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_bankaccount_qr_template'),
    ]

    operations = [
        migrations.RunPython(update_qr_template, reverse_qr_template),
    ]

