# Generated by Django 5.2.10 on 2026-01-12 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredient', '0002_alter_ingredient_options_ingredient_cost_per_unit_and_more'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToppingRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping_recipes', to='ingredient.ingredient')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='menu.topping')),
            ],
            options={
                'db_table': 'topping_recipes',
                'ordering': ['topping', 'ingredient'],
                'unique_together': {('topping', 'ingredient')},
            },
        ),
        migrations.CreateModel(
            name='VariantRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_recipes', to='ingredient.ingredient')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='menu.productvariant')),
            ],
            options={
                'db_table': 'variant_recipes',
                'ordering': ['variant', 'ingredient'],
                'unique_together': {('variant', 'ingredient')},
            },
        ),
    ]
