# Generated by Django 5.2.10 on 2026-03-10 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('water', 'Thêm nước lọc'), ('utensils', 'Thêm bát đũa'), ('clean_table', 'Dọn bàn'), ('consultation', 'Tư vấn món'), ('other', 'Khác')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Ghi chú thêm từ khách hàng', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('response_time_seconds', models.IntegerField(blank=True, help_text='Thời gian phản hồi (giây)', null=True)),
                ('completion_time_seconds', models.IntegerField(blank=True, help_text='Thời gian hoàn thành (giây)', null=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_calls', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_calls', to='tables.table')),
            ],
            options={
                'db_table': 'staff_calls',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['table', 'status'], name='staff_calls_table_i_db9439_idx'), models.Index(fields=['status', 'created_at'], name='staff_calls_status_17450c_idx'), models.Index(fields=['assigned_staff', 'status'], name='staff_calls_assigne_374141_idx')],
            },
        ),
    ]
